apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-1
spec:
  selector:
    matchLabels:
      app: server-1
  template:
    metadata:
      labels:
        app: server-1
    spec:
      containers:
      - name: server-1
        image: server-1:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9090
