apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-2
spec:
  selector:
    matchLabels:
      app: server-2
  template:
    metadata:
      labels:
        app: server-2
    spec:
      containers:
      - name: server-2
        image: server-2:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9090
